### ISSUE TITLE
Doesn't work with Worldguard 7.0.2

### ISSUE THREAD

**Issue by blenditbeautiful** [Lubdan/WorldGuardDamageMobs#1]
Flag does not appear in flags list and cannot be set with commands.

Minecraft Version: 1.15.2
Worldguard Version: 7.0.2
Paper Version: git-Paper-105 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

17.03 12:42:13 [Server] ERROR Could not pass event EntityDamageByEntityEvent to WorldGuardDamageMobs v1.0
17.03 12:42:13 [Server] INFO java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(Lorg/bukkit/World;)Lcom/sk89q/worldguard/protection/managers/RegionManager;

**Comment by bobhenl** [comment]
bump
